class Role {
  final String id;
  final int createdAt;
  final String roleName;
  final String status;

  Role({
    this.id = '',
    required this.createdAt,
    required this.roleName,
    required this.status,
  });

  // Function to convert a Role into a map
  Map<String, dynamic> toMap() {
    return {
      'id': id, // This is optional because it is generated by Firestore
      'createdAt': createdAt,
      'roleName': roleName,
      'status': status,
    };
  }

  // Function to create a Role from a map
  static Role fromMap(Map<String, dynamic> map) {
    return Role(
      id: map['id'],
      createdAt: map['createdAt'],
      roleName: map['roleName'],
      status: map['status'],
    );
  }
}
